"""InterfaceToDD module - Dragon module call generation."""

from .dragon_module_calls import LIB, MAC, EDI, COMPO, EDI_COMPO, SALT, MCCGT, TRK
from .CLE2000 import (
    CLE2000_MAX_LINE, CLE2000_MAX_VARNAME,
    validate_varname, wrap_cle2000_line,
    CLE2000_procedure, main_procedure, sub_procedure,
)
from .case_generator import DragonCase
from .dragon_runner import DragonRunner, RunResult
from .Serpent2_exports import (
    # Constants and utilities
    REACTION_TO_MT_NUMBER,
    DRAGON_REAC_TO_REACTION_NAME,
    ELEMENT_TO_Z,
    Z_TO_ELEMENT,
    EVALUATION_XS_SUFFIX_MAPS,
    EVALUATION_THERM_SUFFIX_MAPS,
    TEMPERATURE_TO_XS_SUFFIX,
    get_xs_suffix,
    get_therm_suffix,
    get_therm_interpolation_suffixes,
    parse_isotope_name,
    isotope_name_to_zaid_str,
    # Core classes
    S2_Material,
    S2_PinUniverse,
    S2_Lattice,
    S2_ChannelGeometry,
    S2_ControlCrossGeometry,
    S2_EnergyGrid,
    S2_Detector,
    S2_IsotopeResponseMaterial,
    S2_ThermalScattering,
    S2_Settings,
    Serpent2Model,
)

__all__ = ["LIB", 
           "MAC", 
           "EDI", 
           "COMPO", 
           "EDI_COMPO",
           "SALT",
           "MCCGT",
           "TRK",
           "DragonCase",
           "DragonRunner",
           "RunResult",
           "CLE2000_MAX_LINE",
           "CLE2000_MAX_VARNAME",
           "validate_varname",
           "wrap_cle2000_line",
           "CLE2000_procedure",
           "main_procedure",
           "sub_procedure",
           "REACTION_TO_MT_NUMBER",
           "DRAGON_REAC_TO_REACTION_NAME",
           "ELEMENT_TO_Z",
           "Z_TO_ELEMENT",
           "EVALUATION_XS_SUFFIX_MAPS",
           "EVALUATION_THERM_SUFFIX_MAPS",
           "TEMPERATURE_TO_XS_SUFFIX",
           "get_xs_suffix",
           "get_therm_suffix",
           "get_therm_interpolation_suffixes",
           "parse_isotope_name",
           "isotope_name_to_zaid_str",
           "S2_Material",
           "S2_PinUniverse",
           "S2_Lattice",
           "S2_ChannelGeometry",
           "S2_ControlCrossGeometry",
           "S2_EnergyGrid",
           "S2_Detector",
           "S2_IsotopeResponseMaterial",
           "S2_ThermalScattering",
           "S2_Settings",
           "Serpent2Model",
          ]
