# Dragon case execution runner for starterDD.
# Replaces the manual rdragon + .access + .save workflow with
# an integrated, traceable execution pipeline.
#
# R.Guasch — 12/03/2026

import gzip
import logging
import os
import re
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional
from ..DDModel.DragonCalculationScheme import EditionBetweenLevelsStep

import yaml

log = logging.getLogger(__name__)


# -------------------------------------------------------------------
# RunResult – lightweight container for execution outcome
# -------------------------------------------------------------------

@dataclass
class RunResult:
    """Result of a Dragon case execution.

    Attributes
    ----------
    success : bool
        ``True`` if Dragon terminated with "normal end".
    run_directory : str
        Absolute path to the results directory.
    manifest_path : str
        Path to the ``run_manifest.yaml`` inside *run_directory*.
    wall_time_seconds : float
        Wall-clock execution time in seconds.
    return_code : int
        Process return code (0 = ok).
    listing_path : str
        Path to the ``.result`` listing file.
    keff : float or None
        Effective multiplication factor parsed from the listing,
        or ``None`` if not found.
    """

    success: bool
    run_directory: str
    manifest_path: str
    wall_time_seconds: float
    return_code: int
    listing_path: str
    keff: Optional[float] = None


# -------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------

def _build_scheme_descriptor(scheme):
    """Build a directory-name string from a ``DragonCalculationScheme``.

    Format:  ``<SSH_method>_<SSH_spatial>_<N>L_<flux_methods>``

    Examples
    --------
    * 1-level MOC:  ``RSE_IC_1L_MOC``
    * 2-level IC+MOC:  ``RSE_IC_2L_IC_MOC``
    * CP-based:  ``PT_CP_1L_CP``
    """
    ssh_steps = scheme.get_self_shielding_steps()
    flux_steps = scheme.get_flux_steps()

    # Self-shielding descriptor
    if ssh_steps:
        ssh = ssh_steps[0]
        ssh_method = (ssh.self_shielding_method or "RSE").upper()
        ssh_spatial = (ssh.spatial_method or "CP").upper()
    else:
        ssh_method = "UNK"
        ssh_spatial = "UNK"

    # Flux descriptor
    n_levels = len(flux_steps) if flux_steps else 0
    flux_methods = "_".join(
        s.spatial_method.upper() for s in flux_steps
    ) if flux_steps else "NONE"

    # Statepoint count
    n_sp = scheme.get_total_statepoints()
    sp_tag = f"{n_sp}sp" if n_sp > 1 else ""

    parts = [ssh_method, ssh_spatial, f"{n_levels}L", flux_methods]
    if sp_tag:
        parts.append(sp_tag)

    return "_".join(parts)


def _parse_keff_from_listing(listing_path):
    """Parse the last keff value from a Dragon listing file.

    Looks for lines like ``keff= 1.08234`` (printed by the
    generated x2m procedures).

    Returns
    -------
    float or None
    """
    keff = None
    try:
        with open(listing_path) as f:
            for line in f:
                m = re.search(r'keff\s*=\s*([0-9]+\.[0-9]+(?:[eE][+-]?\d+)?)', line)
                if m:
                    keff = float(m.group(1))
    except (OSError, ValueError):
        pass
    return keff


def _check_normal_end(listing_path):
    """Return ``True`` if the listing contains 'normal end'."""
    try:
        with open(listing_path) as f:
            # Check last 30 lines (like rdragon does with tail)
            lines = f.readlines()
            tail = lines[-30:] if len(lines) >= 30 else lines
            return any("normal end" in l.lower() for l in tail)
    except OSError:
        return False


# -------------------------------------------------------------------
# DragonRunner – main execution engine
# -------------------------------------------------------------------

class DragonRunner:
    """Execute a DRAGON5 case generated by ``DragonCase``.

    This class replaces the ``rdragon`` + ``.access`` + ``.save``
    workflow with a Python-native, traceable execution pipeline.

    Parameters
    ----------
    dragon_case : DragonCase
        A case that has already called
        ``generate_cle2000_procedures()``.
    dragon_executable : str or None
        Absolute path to the Dragon binary.
        Resolution order: explicit argument → ``$dragon_exec``
        → ``$DRAGON_EXEC`` → error.
    draglib_paths : dict or None
        ``{draglib_file_name: absolute_path}``.
        If ``None``, looks in ``$DRAGLIBS`` directory for files
        matching the draglib names in the case.
    results_root : str
        Root directory for results.
    num_threads : int
        OpenMP thread count (``OMP_NUM_THREADS``).
    create_latest_symlink : bool
        If ``True``, maintain a ``latest`` symlink pointing
        to the most recent run directory.
    """

    def __init__(
        self,
        dragon_case,
        dragon_executable=None,
        draglib_paths=None,
        results_root="./results",
        num_threads=1,
        create_latest_symlink=True,
    ):
        self.case = dragon_case
        # Store raw arguments — resolution is deferred to run()
        # so that dry_run works without a real executable or
        # draglib files on disk.
        self._raw_executable = dragon_executable
        self._raw_draglib_paths = draglib_paths
        self.dragon_executable = None
        self.draglib_paths = draglib_paths or {}
        self.results_root = os.path.abspath(results_root)
        self.num_threads = num_threads
        self.create_latest_symlink = create_latest_symlink

        # Populated after generate_cle2000_procedures
        self._procedure_files = None
        self._scheme = None

    # -----------------------------------------------------------
    # Resolution helpers
    # -----------------------------------------------------------

    @staticmethod
    def _resolve_executable(explicit_path):
        """Resolve the Dragon executable path.
        
        Dragon executable is located in Dragon/bin/<platform>/Dragon

        Resolution order:
        1. Explicit argument (if given and exists).
        2. ``$dragon_exec`` environment variable.
        3. ``$DRAGON_EXEC`` environment variable.
        4. Raise ``FileNotFoundError``.
        """
        candidates = [
            explicit_path,
            os.environ.get("dragon_exec"),
            os.environ.get("DRAGON_EXEC"),
        ]
        for path in candidates:
            if path and os.path.isfile(path):
                return os.path.abspath(path)

        searched = [c for c in candidates if c]
        raise FileNotFoundError(
            "Cannot find Dragon executable. "
            "Provide dragon_executable= argument, or set "
            "$dragon_exec or $DRAGON_EXEC environment variable. "
            f"Searched: {searched} \n"
            "Dragon executable is located in Dragon/bin/<platform>/Dragon"
        )

    def _resolve_draglib_paths(self, explicit_paths):
        """Resolve draglib file paths.

        Resolution order per library:
        1. Explicit ``draglib_paths`` dict.
        2. ``$DRAGLIBS`` directory (search for matching filenames).
        3. Raise ``FileNotFoundError``.

        Returns
        -------
        dict
            ``{draglib_name: absolute_path}``
        """
        explicit_paths = explicit_paths or {}
        resolved = {}

        for draglib_name in self.case.draglib_name_to_alias:
            # 1. Explicit path
            if draglib_name in explicit_paths:
                p = explicit_paths[draglib_name]
                if os.path.isfile(p):
                    resolved[draglib_name] = os.path.abspath(p)
                    continue
                # Also check .gz
                if os.path.isfile(str(p) + ".gz"):
                    resolved[draglib_name] = os.path.abspath(
                        str(p) + ".gz"
                    )
                    continue

            # 2. Search well-known env vars: DRAGLIBS_DIR, DRAGLIB_DIR, DRAGLIBS
            _ENV_VARS = ("DRAGLIBS_DIR", "DRAGLIB_DIR", "DRAGLIBS")
            draglibs_dir = next(
                (os.environ[v] for v in _ENV_VARS if v in os.environ),
                None,
            )
            if draglibs_dir and os.path.isdir(draglibs_dir):
                candidate = os.path.join(draglibs_dir, draglib_name)
                if os.path.isfile(candidate):
                    resolved[draglib_name] = os.path.abspath(candidate)
                    continue
                if os.path.isfile(candidate + ".gz"):
                    resolved[draglib_name] = os.path.abspath(
                        candidate + ".gz"
                    )
                    continue

            env_vals = {v: os.environ.get(v, "(not set)") for v in _ENV_VARS}
            raise FileNotFoundError(
                f"Cannot find draglib '{draglib_name}'. "
                f"Provide it via draglib_paths= argument, "
                f"or place it (optionally gzip-compressed) in the directory "
                f"pointed to by one of: {', '.join(f'${v}' for v in _ENV_VARS)}. "
                f"Current values: {env_vals}"
            )

        return resolved

    # -----------------------------------------------------------
    # Scheme descriptor
    # -----------------------------------------------------------

    def _get_scheme_descriptor(self):
        """Build a descriptive directory name from the scheme."""
        if self._scheme is None:
            raise RuntimeError(
                "Scheme not available. Call "
                "generate_cle2000_procedures() first."
            )
        return _build_scheme_descriptor(self._scheme)

    # -----------------------------------------------------------
    # Run directory construction
    # -----------------------------------------------------------

    def _build_run_directory(self, timestamp):
        """Create and return the structured results directory.

        Structure::

            <results_root>/
            └── <case_name>/
                └── <scheme_descriptor>/
                    └── <timestamp>/

        Parameters
        ----------
        timestamp : str
            ISO-format timestamp (filesystem-safe).

        Returns
        -------
        str
            Absolute path to the run directory.
        """
        scheme_desc = self._get_scheme_descriptor()
        run_dir = os.path.join(
            self.results_root,
            self.case.case_name,
            scheme_desc,
            timestamp,
        )
        os.makedirs(run_dir, exist_ok=True)
        os.makedirs(
            os.path.join(run_dir, "inputs"), exist_ok=True
        )
        os.makedirs(
            os.path.join(run_dir, "procedures"), exist_ok=True
        )
        return run_dir

    def _update_latest_symlink(self, run_dir):
        """Create or update the ``latest`` symlink.

        The symlink is placed alongside the timestamped run
        directories, under ``<case_name>/<scheme_descriptor>/``.
        """
        parent = os.path.dirname(run_dir)
        latest = os.path.join(parent, "latest")
        target = os.path.basename(run_dir)
        # Atomic update: remove then recreate
        try:
            if os.path.islink(latest):
                os.remove(latest)
            os.symlink(target, latest)
        except OSError:
            pass  # Non-critical; skip on Windows etc.

    # -----------------------------------------------------------
    # Input staging (replaces .access script)
    # -----------------------------------------------------------

    def _stage_inputs(self, run_dir, staging_dir,
                      skip_draglibs=False):
        """Copy/symlink all required files into the staging directory.

        This replaces the hand-written ``.access`` shell scripts.

        Parameters
        ----------
        run_dir : str
            The final results directory (for archiving configs).
        staging_dir : str
            The temporary execution directory (where Dragon runs).
        skip_draglibs : bool
            If ``True``, skip draglib staging (used in dry-run
            mode when draglib paths may not be resolved yet).
        """
        # 1. Copy CLE2000 procedures into staging dir
        for key, path in self._procedure_files.items():
            # Safety check: skip any entries that are lists (MIXEQ compatibility)
            if isinstance(path, list):
                continue
            src = os.path.abspath(path)
            if os.path.isfile(src):
                dst = os.path.join(
                    staging_dir, os.path.basename(src)
                )
                shutil.copy2(src, dst)
                # Also archive in run_dir/procedures/
                shutil.copy2(
                    src,
                    os.path.join(
                        run_dir, "procedures",
                        os.path.basename(src),
                    ),
                )

        # 2. Symlink TDT geometry files
        tdt_path = os.path.abspath(self.case.tdt_path)

        # Check if we have tracked TDT files from procedure generation
        if hasattr(self.case, 'tdt_files_used') and self.case.tdt_files_used:
            # Create standardized symlinks pointing to actual full-named TDT files
            # The x2m uses standardized names (short enough for CLE2000)
            # but they must point to the actual full-named files in tdt_path
            log.info(
                f"Staging {len(self.case.tdt_files_used)} TDT file(s) "
                f"with standardized names pointing to full names"
            )
            
            # Get file mapping that was created during procedure generation
            tdt_file_mapping = getattr(self.case, 'tdt_file_mapping', {})
            
            for step_name, actual_tdt_filename in self.case.tdt_files_used.items():
                # Get the standardized filename from the mapping (computed in case_generator)
                if step_name in tdt_file_mapping:
                    standardized_filename = tdt_file_mapping[step_name].get('standardized')
                else:
                    # Fallback: try to reconstruct from step (but this may fail in tests)
                    standardized_filename = None
                    if (hasattr(self.case, 'scheme') and 
                        self.case.scheme is not None and
                        hasattr(self.case.scheme, 'get_trackable_steps')):
                        try:
                            for s in self.case.scheme.get_trackable_steps():
                                if s.name == step_name:
                                    suffix = "_MACRO" if s.export_macros else ""
                                    standardized_filename = (
                                        f"{self.case.case_name}_{s.name}"
                                        f"_{s.spatial_method}_{s.tracking}{suffix}.dat"
                                    )
                                    break
                        except (TypeError, AttributeError):
                            pass
                
                if standardized_filename is None:
                    log.error(
                        f"Could not determine standardized filename for step '{step_name}'. "
                        f"No mapping found and scheme lookup failed."
                    )
                    raise ValueError(
                        f"Cannot determine standardized filename for step '{step_name}'. "
                        f"Check that tdt_file_mapping was populated during procedure generation."
                    )
                
                # Source: actual full-named file in tdt_path
                src = os.path.join(tdt_path, actual_tdt_filename)
                # Destination: standardized symlink in staging directory
                dst = os.path.join(staging_dir, standardized_filename)
                
                # Validate source file exists before attempting to symlink
                if not os.path.isfile(src):
                    available_files = os.listdir(tdt_path) if os.path.isdir(tdt_path) else []
                    log.error(
                        f"[ERROR] TDT file not found for step '{step_name}':\n"
                        f"  Expected: {src}\n"
                        f"  Actual name: {actual_tdt_filename}\n"
                        f"  TDT directory: {tdt_path}\n"
                        f"  Available files in tdt_path: {available_files}"
                    )
                    raise FileNotFoundError(
                        f"TDT file not found for step '{step_name}': {src}\n"
                        f"Expected actual filename: {actual_tdt_filename}\n"
                        f"Make sure the TDT file exists and tdt_path is set correctly."
                    )
                
                # Create standardized symlink if destination doesn't exist
                # Use os.path.lexists() to detect both valid and broken symlinks
                # (os.path.exists() returns False for broken symlinks, but they
                #  still exist as paths, causing os.symlink() to raise FileExistsError)
                if os.path.lexists(dst):
                    # Path exists (valid link or broken link)
                    if os.path.islink(dst):
                        # It's a symlink - check if it's broken or points to wrong target
                        current_target = os.readlink(dst)
                        if current_target == src:
                            # Already points to correct source, skip
                            log.debug(
                                f"[OK] Staging symlink already correct for step '{step_name}': {dst}"
                            )
                        else:
                            # Broken or points to wrong file - replace it
                            os.remove(dst)
                            os.symlink(src, dst)
                            log.info(
                                f"[REPLACED] TDT staging symlink for step '{step_name}':\n"
                                f"  Standardized name: {standardized_filename}\n"
                                f"  Points to actual: {actual_tdt_filename}\n"
                                f"  Link: {dst} -> {src}"
                            )
                    else:
                        # It's a regular file - this is an error, don't overwrite
                        log.error(
                            f"[ERROR] Staging path exists as a regular file for step '{step_name}': {dst}"
                        )
                        raise FileExistsError(
                            f"Staging path is a regular file (not a symlink) for step '{step_name}': {dst}"
                        )
                else:
                    # Path doesn't exist - create new symlink
                    os.symlink(src, dst)
                    log.info(
                        f"[OK] Staged TDT for step '{step_name}':\n"
                        f"  Standardized name: {standardized_filename}\n"
                        f"  Points to actual: {actual_tdt_filename}\n"
                        f"  Link: {dst} -> {src}"
                    )
                
                # Validate that staging symlink resolves correctly
                if os.path.islink(dst) and not os.path.exists(dst):
                    log.error(
                        f"[ERROR] TDT staging symlink is broken for step '{step_name}': {dst}"
                    )
                    raise FileNotFoundError(
                        f"TDT staging symlink broken for step '{step_name}': {dst} -> {src}"
                    )

        elif os.path.isdir(tdt_path):
            # Fallback: symlink all .dat files (legacy behavior)
            log.warning(
                "No tracked TDT files available. "
                "Symlinking all .dat files (legacy behavior). "
                "This may symlink unintended files if multiple TDT "
                "generations have occurred."
            )
            for fname in os.listdir(tdt_path):
                if fname.endswith(".dat"):
                    src = os.path.join(tdt_path, fname)
                    dst = os.path.join(staging_dir, fname)
                    if not os.path.exists(dst):
                        os.symlink(src, dst)
        elif os.path.isfile(tdt_path):
            # Single file case (unchanged)
            dst = os.path.join(
                staging_dir, os.path.basename(tdt_path)
            )
            if not os.path.exists(dst):
                os.symlink(tdt_path, dst)

        # 3. Symlink draglib files (unless skipped for dry_run)
        if not skip_draglibs:
            self._stage_draglibs(staging_dir)

    @staticmethod
    def _ensure_decompressed(draglib_path):
        """Return a path to an uncompressed copy of *draglib_path*.

        If *draglib_path* ends with ``.gz``, the file is decompressed
        to a persistent sibling path (the same name without the
        ``.gz`` suffix).  Decompression is skipped when the sibling
        already exists **and** is at least as new as the archive, so
        subsequent runs reuse the cached copy without re-reading the
        full archive.

        Parameters
        ----------
        draglib_path : str
            Absolute path to the draglib file, possibly gzip-compressed.

        Returns
        -------
        str
            Absolute path to the uncompressed draglib file.
        """
        draglib_path = str(draglib_path)

        if not draglib_path.endswith(".gz"):
            return draglib_path

        unzipped_path = draglib_path[:-3]  # strip ".gz"

        # Reuse cached decompressed file if it is fresh enough.
        if os.path.isfile(unzipped_path):
            gz_mtime = os.path.getmtime(draglib_path)
            uz_mtime = os.path.getmtime(unzipped_path)
            if uz_mtime >= gz_mtime:
                log.info(
                    "Draglib cache hit: reusing '%s'", unzipped_path
                )
                return unzipped_path
            log.info(
                "Draglib cache stale (archive newer): re-decompressing '%s'",
                draglib_path,
            )
        else:
            log.info("Decompressing draglib '%s' ...", draglib_path)

        tmp_path = unzipped_path + ".tmp"
        try:
            with gzip.open(draglib_path, "rb") as f_in:
                with open(tmp_path, "wb") as f_out:
                    shutil.copyfileobj(f_in, f_out)
            os.replace(tmp_path, unzipped_path)
        except Exception:
            # Remove partial file so a retry starts clean.
            if os.path.exists(tmp_path):
                os.remove(tmp_path)
            raise

        log.info("Decompressed draglib to '%s'", unzipped_path)
        return unzipped_path

    def _stage_draglibs(self, staging_dir):
        """Symlink draglib files into the staging directory.

        For gzip-compressed draglibs, decompression is handled by
        :meth:`_ensure_decompressed`, which caches the result next to
        the archive so subsequent runs skip re-decompression.

        The CLE2000 alias symlink always points to the uncompressed
        file, never to the ``.gz`` archive.
        """
        for draglib_name, draglib_path in self.draglib_paths.items():
            log.info(
                "Staging draglib '%s' from '%s'",
                draglib_name, draglib_path,
            )
            unzipped_path = self._ensure_decompressed(draglib_path)

            alias = self.case.draglib_name_to_alias[draglib_name]
            dst = os.path.join(staging_dir, alias)

            if not os.path.exists(dst):
                os.symlink(os.path.abspath(unzipped_path), dst)

            # Validate that the symlink resolves to a readable file.
            if not os.path.exists(dst):
                raise FileNotFoundError(
                    f"Draglib symlink '{dst}' -> '{unzipped_path}' "
                    f"does not resolve. Check that the file exists "
                    f"and is readable."
                )

            log.info(
                "Staged draglib '%s' as alias '%s' -> '%s'",
                draglib_name, alias, unzipped_path,
            )

    # -----------------------------------------------------------
    # Config YAML archival
    # -----------------------------------------------------------

    def _archive_config_yamls(self, run_dir):
        """Copy the original configuration YAML files into the
        run directory's ``inputs/`` sub-directory.

        This provides a frozen snapshot of what was run.
        """
        inputs_dir = os.path.join(run_dir, "inputs")
        for key, yaml_path in self.case.config_yamls.items():
            src = os.path.abspath(yaml_path)
            if os.path.isfile(src):
                dst = os.path.join(
                    inputs_dir, os.path.basename(src)
                )
                shutil.copy2(src, dst)

    # -----------------------------------------------------------
    # Run manifest
    # -----------------------------------------------------------

    def _write_run_manifest(self, run_dir, timestamp):
        """Write the traceability manifest before execution.

        Returns the manifest dict (to be updated after execution).
        """
        from .. import __version__

        manifest = {
            "starterDD_version": __version__,
            "run_timestamp": timestamp,
            "case_name": self.case.case_name,
            "assembly_id": self.case.case_name,
            "dragon_executable": self.dragon_executable,
            "draglibs": dict(
                self.case.draglib_name_to_alias
            ),
            "draglib_paths": {
                k: str(v)
                for k, v in self.draglib_paths.items()
            },
            "calculation_scheme": self._build_scheme_manifest(),
            "config_yamls": {
                key: os.path.basename(path)
                for key, path in self.case.config_yamls.items()
            },
            "num_threads": self.num_threads,
            "execution": None,  # filled after run
        }

        manifest_path = os.path.join(
            run_dir, "run_manifest.yaml"
        )
        with open(manifest_path, "w") as f:
            yaml.dump(
                manifest, f,
                default_flow_style=False,
                sort_keys=False,
            )

        return manifest, manifest_path

    def _build_scheme_manifest(self):
        """Build a dict summarising the calculation scheme for
        the manifest."""
        scheme = self._scheme
        steps_info = []
        for s in scheme.steps:
            if isinstance(s, EditionBetweenLevelsStep):
                step_dict = {
                    "name": s.name,
                    "type": s.step_type,
                    "number_of_macro_groups": s.number_of_macro_groups,
                    "energy_groups_bounds": s.energy_groups_bounds,
                    "sph_correction": s.sph_correction,
                    "max_sph_group": s.max_sph_group,
                }
            else:  # CalculationStep
                step_dict = {
                    "name": s.name,
                    "type": s.step_type,
                    "method": s.spatial_method,
                    "tracking": s.tracking,
                }
                if s.step_type == "self_shielding":
                    step_dict["ssh_module"] = s.self_shielding_module
                    step_dict["ssh_method"] = s.self_shielding_method
                if s.flux_level is not None:
                    step_dict["flux_level"] = s.flux_level
            steps_info.append(step_dict)

        branches_info = {}
        for b in scheme.branches:
            branches_info[b.type] = b.values

        outputs_info = [o.name for o in scheme.outputs]
        
        # Build TDT file mapping information (Phase 3: Diagnostics)
        tdt_info = []
        if hasattr(self.case, 'tdt_file_mapping'):
            for step_name, mapping in self.case.tdt_file_mapping.items():
                tdt_info.append({
                    'step_name': step_name,
                    'actual_filename': mapping.get('actual'),
                    'standardized_filename': mapping.get('standardized'),
                    'names_match': mapping.get('match'),
                })

        return {
            "name": scheme.name,
            "descriptor": self._get_scheme_descriptor(),
            "steps": steps_info,
            "branches": branches_info,
            "total_statepoints": scheme.get_total_statepoints(),
            "outputs": outputs_info,
            "tdt_files": tdt_info,
        }

    def _update_manifest_with_results(
        self, manifest, manifest_path, run_result
    ):
        """Update the manifest file with execution results."""
        manifest["execution"] = {
            "success": run_result.success,
            "return_code": run_result.return_code,
            "wall_time_seconds": round(
                run_result.wall_time_seconds, 2
            ),
            "keff": run_result.keff,
        }
        with open(manifest_path, "w") as f:
            yaml.dump(
                manifest, f,
                default_flow_style=False,
                sort_keys=False,
            )

    # -----------------------------------------------------------
    # Output collection (replaces .save script)
    # -----------------------------------------------------------

    def _collect_outputs(self, staging_dir, run_dir):
        """Move result files from the staging directory to the
        run directory.

        Collects:
        - ``.result`` listing file
        - ``_CPO_*`` COMPO binary files
        - ``.ps`` PostScript visualisation files
        - Any other output files not matching input patterns
        """
        case_name = self.case.case_name

        # 1. .result listing
        result_file = os.path.join(
            staging_dir, f"{case_name}.result"
        )
        if os.path.isfile(result_file):
            shutil.move(
                result_file,
                os.path.join(
                    run_dir, f"{case_name}.result"
                ),
            )

        # 2. _CPO_* COMPO files
        for fname in os.listdir(staging_dir):
            if fname.startswith("_CPO_"):
                shutil.move(
                    os.path.join(staging_dir, fname),
                    os.path.join(run_dir, fname),
                )

        # 3. PostScript files
        for fname in os.listdir(staging_dir):
            if fname.endswith(".ps"):
                shutil.move(
                    os.path.join(staging_dir, fname),
                    os.path.join(run_dir, fname),
                )

        # 4. Any .DBDATA or other Dragon output binaries
        for fname in os.listdir(staging_dir):
            if fname.endswith(".DBDATA"):
                shutil.move(
                    os.path.join(staging_dir, fname),
                    os.path.join(run_dir, fname),
                )

    # -----------------------------------------------------------
    # Execution
    # -----------------------------------------------------------

    def run(self, dry_run=False):
        """Execute the Dragon case.

        Parameters
        ----------
        dry_run : bool
            If ``True``, stage all inputs and write the manifest
            but do **not** execute Dragon.  Useful for debugging
            the setup.

        Returns
        -------
        RunResult
        """
        # Ensure procedures have been generated
        if not hasattr(self.case, "scheme") or self.case.scheme is None:
            procs = self.case.generate_cle2000_procedures()
        else:
            # Procedures already generated; check if we have the full dict stored
            if hasattr(self.case, '_procedure_files') and self.case._procedure_files:
                procs = self.case._procedure_files
            else:
                # Fallback: manually construct dict (without MIXEQ procedures)
                procs = {
                    "x2m": os.path.join(
                        self.case.output_path,
                        f"{self.case.case_name}.x2m",
                    ),
                    "mix": os.path.join(
                        self.case.output_path,
                        f"MIX.c2m",
                    ),
                    "trk": os.path.join(
                        self.case.output_path,
                        f"TRK.c2m",
                    ),
                    "edir": os.path.join(
                        self.case.output_path,
                        f"EDIR.c2m",
                    ),
                }

        self._procedure_files = procs
        self._scheme = self.case.scheme

        # Timestamp for this run
        now = datetime.now()
        timestamp = now.strftime("%Y-%m-%dT%H-%M-%S")

        # Build results directory
        run_dir = self._build_run_directory(timestamp)

        # Archive config YAMLs
        self._archive_config_yamls(run_dir)

        # Create staging (temp) directory
        staging_dir = tempfile.mkdtemp(
            prefix=f"dragon_{self.case.case_name}_"
        )

        try:
            # --- Resolve executable & draglibs early so that
            # _stage_inputs (which calls _stage_draglibs) sees
            # string paths, not raw PosixPath objects, and so
            # that the manifest records the resolved values. ---
            if not dry_run:
                self.dragon_executable = self._resolve_executable(
                    self._raw_executable
                )
                self.draglib_paths = self._resolve_draglib_paths(
                    self._raw_draglib_paths
                )

            # Write pre-execution manifest (after resolution so
            # that dragon_executable and draglib_paths are filled)
            manifest, manifest_path = self._write_run_manifest(
                run_dir, timestamp
            )

            # Stage inputs (procedures + TDT files + draglibs).
            # Draglib staging is skipped in dry_run when paths
            # are not resolved.
            self._stage_inputs(run_dir, staging_dir,
                               skip_draglibs=dry_run)

            if dry_run:
                # In dry_run mode, copy the staging dir contents
                # to run_dir for inspection, but don't execute.
                staging_listing = os.path.join(
                    run_dir, "_staging_contents.txt"
                )
                with open(staging_listing, "w") as f:
                    f.write(
                        f"Staging directory: {staging_dir}\n"
                    )
                    f.write("Contents:\n")
                    for fname in sorted(os.listdir(staging_dir)):
                        fpath = os.path.join(
                            staging_dir, fname
                        )
                        if os.path.islink(fpath):
                            target = os.readlink(fpath)
                            f.write(
                                f"  {fname} -> {target}\n"
                            )
                        else:
                            size = os.path.getsize(fpath)
                            f.write(
                                f"  {fname} ({size} bytes)\n"
                            )

                manifest["execution"] = {
                    "dry_run": True,
                    "staging_listing": staging_listing,
                }
                with open(manifest_path, "w") as f:
                    yaml.dump(
                        manifest, f,
                        default_flow_style=False,
                        sort_keys=False,
                    )

                return RunResult(
                    success=True,
                    run_directory=run_dir,
                    manifest_path=manifest_path,
                    wall_time_seconds=0.0,
                    return_code=0,
                    listing_path="",
                    keff=None,
                )

            # Copy executable into staging dir
            exec_dst = os.path.join(staging_dir, "code")
            shutil.copy2(self.dragon_executable, exec_dst)
            os.chmod(exec_dst, 0o755)

            # Prepare input dataset
            x2m_name = os.path.basename(
                self._procedure_files["x2m"]
            )
            dataset_path = os.path.join(
                staging_dir, x2m_name
            )

            # Execute
            env = os.environ.copy()
            env["OMP_NUM_THREADS"] = str(self.num_threads)
            env["NO_STOP_MESSAGE"] = "1"

            t_start = time.time()

            with open(dataset_path, "r") as stdin_f:
                proc = subprocess.run(
                    ["./code"],
                    stdin=stdin_f,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    cwd=staging_dir,
                    env=env,
                )

            wall_time = time.time() - t_start

            # Write listing to staging dir
            result_filename = (
                f"{self.case.case_name}.result"
            )
            listing_staging = os.path.join(
                staging_dir, result_filename
            )
            with open(listing_staging, "wb") as f:
                f.write(proc.stdout)

            # Collect outputs
            self._collect_outputs(staging_dir, run_dir)

            # Parse results
            listing_final = os.path.join(
                run_dir, result_filename
            )
            success = _check_normal_end(listing_final)
            keff = _parse_keff_from_listing(listing_final)

            result = RunResult(
                success=success,
                run_directory=run_dir,
                manifest_path=manifest_path,
                wall_time_seconds=wall_time,
                return_code=proc.returncode,
                listing_path=listing_final,
                keff=keff,
            )

            # Update manifest with results
            self._update_manifest_with_results(
                manifest, manifest_path, result
            )

            # Update latest symlink
            if self.create_latest_symlink:
                self._update_latest_symlink(run_dir)

            return result

        finally:
            # Cleanup staging directory
            if os.path.isdir(staging_dir):
                shutil.rmtree(
                    staging_dir, ignore_errors=True
                )
