# class defining an assembly model for Dragon claculations. 
# R.Guasch
# Date : 09/02/2026 [created] 

from starterDD.GeometryBuilder.helpers import computeSantamarinaradii
import yaml

class AssemblyModel:
    """
    Class representing an assembly / fuel bundle for DRAGON calculations. 
    Minimal atributes :
        - tdt_file : path to the tdt file generated by glow for the assembly or to be generated
        - lattice_description : description of the lattice (n by m grid) containing the material description of each pin.
        
    Methods :
        - number_fuel_material_mixtures : method to assign a material mixture index to each "physical" property of the fuel in the assembly. 
        - build_calculation_scheme : method to build the calculation scheme to treat the assembly in Dragon.
    """

    def __init__(self, name, tdt_file, geometry_description_yaml):
        self.name = name
        self.tdt_file = tdt_file
        self.parse_geometry_description(geometry_description_yaml)
        self.rod_ID_to_material_dict = None # this will be set later based on the material composition definition selected for the assembly, which can be based on rod IDs in the lattice description for example, in which case this dictionary will map rod IDs to material names for the fuel in the assembly.
        self.lattice = None # this will be a data structure representing the lattice of the assembly, which can be a 2D list of pin models corresponding to the lattice description, for example.

    def parse_geometry_description(self, geometry_description_yaml):
        """
        The yaml file at geometry_description_yaml should contain the following information :
        In the ASSEMBLY_GEOMETRY section :
            - lattice_description : n by m grid describing the material composition of each pin in the assembly (eg. for a 10 by 10 BWR assembly, a 10 by 10 grid with entries like "ROD1", "ROD5G", etc ... describing the fuel material in each pin)
            /!\ convention is x-inreasing y-increasing : 
                - the first row is the "bottom of the lattice" ordered in x-increasing direction, 
                - the last row is the "top of the lattice",
                - the first column is the "left of the lattice" ordered in y-increasing direction, 
                - the last column is the "right of the lattice".
            - assembly_pitch : pitch of the assembly lattice
            - gap_wide : width of the gap between fuel pins in the assembly
            - channel_box_thickness : thickness of the channel box surrounding the fuel pins in the assembly (if any)
            - corner_inner_radius_of_curvature : inner radius of curvature for the corners of the fuel pins in the assembly (if any)
            - Gd_rod_ids : list of material descriptors in the lattice description corresponding to Gd-bearing fuel pins, which should be treated with specific self-shielding
        As well as the PIN_GEOMETRY section describing the geometry of the different types of pins in the assembly (eg. fuel pin, guide tube, etc ...), with the following information for each type of pin :
            - fuel_radius : radius of the fuel region in the pin
            - gap_radius : radius of the gap region in the pin (if any)
            - clad_radius : radius of the cladding region in the pin (if any)
            - height : height of the pin
            - self_shielding_option : self-shielding treatment option for the pin, which can be "Santamarina" to use the Santamarina radii definition for the fuel region, "user_defined" to use user-defined radii for the fuel region (which should be provided in a list in the user_defined_radii field in the yaml file), or "automatic" to automatically subdivide the fuel region into a given number of radial zones for self-shielding treatment (the number of radial zones should be provided in the num_radial_zones field in the yaml file).
            - options_dict : dictionary containing additional options for the pin geometry and self-shielding treatment, such as the list of user-defined radii for the fuel region if the user_defined self-shielding option is selected, or the number of radial zones if the automatic self-shielding option is selected.
        """
        with open(geometry_description_yaml, 'r') as file:
            yaml_data = yaml.safe_load(file)

        self.lattice_description = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("lattice_description", [])
        self.assembly_pitch = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("assembly_pitch", None)
        self.gap_wide = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("gap_wide", None)
        self.channel_box_thickness = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("channel_box_thickness", None)
        self.corner_inner_radius_of_curvature = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("corner_inner_radius_of_curvature", None)
        self.Gd_rod_ids = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("Gd_rod_ids", [])
        self.geometry_type = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("lattice_type", "cartesian") # by default, assume cartesian geometry for the assembly
        self.reactor_type = yaml_data.get("ASSEMBLY_GEOMETRY", {}).get("reactor_type", "BWR") # by default, assume BWR type for the assembly, which can be used to define default self-shielding treatment strategies for the pins in the assembly based on the reactor type if no specific self-shielding option is provided for the pins in the geometry description.

        # Pincell information
        self.pin_geometry_dict = yaml_data.get("PIN_GEOMETRY", {})


    def analyze_lattice_description(self, build_pins = True):
        # create a n by m grid of pin models based on the lattice description and pin geometry information provided in the geometry description yaml file, and store it in the lattice attribute of the assembly model.
        self.lattice = []
        for row in self.lattice_description:
            lattice_row = []
            for descriptor in row:
                if self.rod_ID_to_material_dict is not None:
                    material_name = self.rod_ID_to_material_dict.get(descriptor, None)
                    print(f"Descriptor {descriptor} mapped to material name {material_name} based on rod ID to material mapping.")
                else:                    
                    material_name = None
                pin_geometry_info = self.pin_geometry_dict # for now assume all pins have the same geometry information, but this can be updated later to allow for different pin geometries based on the material or rod ID for example by changing the structure of the pin_geometry_dict in the geometry description yaml file to allow for different geometry information for different types of pins.
                if pin_geometry_info is not None:
                    fuel_radius = pin_geometry_info.get("fuel_radius", None)
                    gap_radius = pin_geometry_info.get("gap_radius", None)
                    clad_radius = pin_geometry_info.get("clad_radius", None)
                    height = pin_geometry_info.get("height", None)
                    self_shielding_option = pin_geometry_info.get("self_shielding_option", None)
                    options_dict = pin_geometry_info.get("options_dict", None)
                    if build_pins:
                        if descriptor in self.Gd_rod_ids:
                            isGd = True
                        else:     
                            isGd = False
                        pin_model = CartesianPinModel(fuel_material_name=material_name, radii=[fuel_radius, gap_radius, clad_radius], height=height, isGd=isGd, self_shielding_option=self_shielding_option, options_dict=options_dict)
                        # set the position of the pin in the lattice based on its indices in the lattice description
                        x_index = self.lattice_description.index(row)
                        y_index = row.index(descriptor)
                        pin_model.set_position_in_lattice(x_index, y_index)
                        # set the temperatures for the pin based on the uniform temperatures defined for the assembly
                        pin_model.set_fuel_temperature(self.fuel_temperature)
                        pin_model.set_clad_temperature(self.structural_temperature)
                        pin_model.set_gap_temperature(self.gap_temperature)
                        pin_model.set_coolant_temperature(self.coolant_temperature)
                        lattice_row.append(pin_model)
                    else:
                        lattice_row.append(descriptor) # if not building the pin models, just store the descriptor in the lattice data structure for now
                else:
                    lattice_row.append(descriptor) # if no specific geometry information is provided for the pin, just store the descriptor in the lattice data structure for now
            self.lattice.append(lattice_row)


    def add_pin_to_lattice(self, pin_model):
        """
        add a pin model to the lattice based on its position defined by its x and y indices in the lattice description of the assembly model.
        """
        x_index = pin_model.x_index
        y_index = pin_model.y_index
        # add the pin model to the lattice at the corresponding position
        self.lattice[x_index][y_index] = pin_model


    def number_fuel_material_mixtures(self, numbering_strategy = "by_material", material_mixtures_dict = None):
        """
        assign a material mixture index to each "physical" property of the fuel in the assembly based on a given numbering strategy, which can be "by_material" to assign the same material mixture index to all pins with the same fuel material, "by_pin" to assign a different material mixture index to each pin in the assembly, or "custom" to use a custom numbering strategy defined by the user through a provided material_mixtures_dict dictionary mapping pin descriptors in the lattice description to material mixture indices.
        """
        pass


                
    def set_rod_ID_to_material_mapping(self, rod_ID_to_material_dict):
        """
        Set the mapping between rod IDs in the lattice description and material names for the fuel in the assembly, which can be used to assign material properties to the different pins in the assembly based on their rod ID in the lattice description.
        """
        self.rod_ID_to_material_dict = rod_ID_to_material_dict
        return


    def set_uniform_temperatures(self, fuel_temperature, gap_temperature, coolant_temperature, moderator_temperature, structural_temperature):
        """
        set uniform temperatures for the different materials in the assembly, which can be used for temperature-dependent self-shielding treatment in Dragon.
        """
        self.fuel_temperature = fuel_temperature
        self.gap_temperature = gap_temperature
        self.coolant_temperature = coolant_temperature
        self.moderator_temperature = moderator_temperature
        self.structural_temperature = structural_temperature
        return

class CartesianPinModel:
    """
    Class representing a pin in a cartesian assembly for DRAGON calculations. 
    Minimal atributes :
        - fuel_material_name : name of the fuel material assigned to the pin (eg. UOX16, 24UOX, etc ...)
        - pitch : regular pitch of the pin in the lattice
        - radii : list of radii for concentric cylindrical regions in the pin (eg. fuel, cladding, gap)
        - region names : list of names for the different regions in the pin (eg. fuel, cladding, gap)
        - height : height of the pin
        - self_shielding_option : by default, use Santamarina radii to define the self-shielding zones in the fuel, but other options could be implemented (eg. user-defined radii, or automatic subdivision into a given number of radial zones)
    Methods :
        - subdivide_into_radial_zones : method to subdivide the pin into radial zones for self-shielding treatment in Dragon.
    """
    def __init__(self, fuel_material_name, radii, height, isGd, self_shielding_option = "Santamarina", options_dict = None):
        self.fuel_material_name = fuel_material_name
        self.radii = radii
        self.height = height
        self.isGd = isGd
        self.self_shielding_option = self_shielding_option

        if self_shielding_option == "Santamarina":
            self.subdivide_into_Santamarina_radii()
        elif self_shielding_option == "user_defined":
            if options_dict is None or "user_defined_radii" not in options_dict:
                raise ValueError("For user-defined self-shielding option, a list of user-defined radii must be provided in the options_dict with key 'user_defined_radii'.")
            self.subdivide_into_user_defined_radii(options_dict["user_defined_radii"])
        elif self_shielding_option == "automatic":
            if options_dict is None or "num_radial_zones" not in options_dict:
                raise ValueError("For automatic self-shielding option, the number of radial zones must be provided in the options_dict with key 'num_radial_zones'.")
            self.subdivide_into_radial_zones(options_dict["num_radial_zones"])
        else:
            raise ValueError(f"Invalid self_shielding_option {self_shielding_option}. Valid options are 'Santamarina', 'user_defined' and 'automatic'.")

        print(f"Created : Pin with fuel material {self.fuel_material_name} subdivided into radial zones with radii {self.radii} based on self-shielding option {self.self_shielding_option}.")

    def subdivide_into_Santamarina_radii(self):
        # code to subdivide the pin into radial zones for self-shielding treatment in Dragon based on the Santamarina radii definition
        self.radii = computeSantamarinaradii(self.radii[0], self.radii[1], self.radii[2], gadolinium=self.isGd)
    
    def subdivide_into_radial_zones(self, num_radial_zones = None):
        # code to subdivide the pin into a given number of radial zones for self-shielding treatment in Dragon based on an automatic subdivision of the fuel region
        pass
    
    def subdivide_into_user_defined_radii(self, user_defined_radii):
        # code to subdivide the pin into radial zones for self-shielding treatment in Dragon based on user-defined radii
        pass

    def set_position_in_lattice(self, x_index, y_index):
        """
        set fuel pincell position in the lattice based on x and y indices in the lattice description of the assembly model. 
        """
        self.x_index = x_index
        self.y_index = y_index

    def set_fuel_temperature(self, fuel_temperature):
        """
        set fuel temperature for the pin, which can be used for temperature-dependent self-shielding treatment in Dragon.
        """
        self.fuel_temperature = fuel_temperature
    
    def set_gap_temperature(self, gap_temperature):
        """
        set gap temperature for the pin.
        """
        self.gap_temperature = gap_temperature
    
    def set_clad_temperature(self, clad_temperature):
        """
        set cladding temperature for the pin, which can be used for temperature-dependent self-shielding treatment in Dragon.
        """
        self.clad_temperature = clad_temperature

    def set_coolant_temperature(self, coolant_temperature):
        """
        set coolant temperature for the pin.
        """
        self.coolant_temperature = coolant_temperature
