# Model instantiation for GE14 benchmark DRAGON treatment
# R.Guasch
# Date : 05/02/2026

from starterDD.MaterialProperties.material_mixture import MaterialMixture, Composition
from starterDD.MaterialProperties.material_mixture import parse_all_compositions_from_yaml
from starterDD.GeometryAnalysis.tdt_parser import read_material_mixture_indices_from_tdt_file

# Goal : Create an assembly model and instantiate the Dragon Calculation Scheme builder
# Model instantiation steps :
flux_tracking_option = "TISO"  # Tracking type for the assembly model
flux_solution = "IC" 
# import macros : true
include_macros = True

# Step 1 : Recover material compositions from the yaml file

path_to_yaml = "BWRProgressionProblems/GE14/inputs/material_compositions.yaml"
compositions = parse_all_compositions_from_yaml(path_to_yaml)

print(compositions)

print(compositions[0].isotopic_composition)
print(compositions[0].isotope_name_composition)
# Step 2 : Recover material numbering from the tdt file generated by glow.
path_to_tdt = "../../glow_data/tdt_data"
file_name = "GE14_simplified"

print([comp.material_name for comp in compositions])
material_mixtures_indices_dict = read_material_mixture_indices_from_tdt_file(path_to_tdt, 
                                                                    file_name, 
                                                                    flux_tracking_option, 
                                                                    include_macros=include_macros, 
                                                                    material_names=[comp.material_name for comp in compositions]
                                                                    )
print(material_mixtures_indices_dict)

# Step 3 : Create material mixtures for the different materials in the assembly based on the selected property assignment strategy.
for material_name, material_mixture_index in material_mixtures_indices_dict.items():
    print(f"Creating material mixture for material {material_name} with index {material_mixture_index}...")
    # find the composition corresponding to the material name
    composition = next((comp for comp in compositions if comp.material_name == material_name), None)
    if composition is None:
        print(f"Error : No composition found for material {material_name}. Skipping material mixture creation.")
        continue
    # create a material mixture with the composition and the material mixture index
    material_mixture = MaterialMixture(material_name=material_name, 
                                        material_mixture_index=material_mixture_index, 
                                        composition=composition, 
                                        temperature=900.0,  # default temperature for now, can be updated later based on user input or tdt file parsing
                                        isdepletable=composition.depletable)
    print(f"Material mixture for material {material_name} created with index {material_mixture_index} and composition {composition.isotopic_composition}.")

# Step 4 : Create the assembly model with the material mixtures, given tdt file and lattice description.

# Step 5 : Instantiate the Dragon Calculation Scheme builder with the assembly model and build the calculation scheme.   


