# Model instantiation for GE14 benchmark DRAGON treatment
# R.Guasch
# Date : 05/02/2026

from starterDD.MaterialProperties.material_mixture import MaterialMixture, Composition
from starterDD.MaterialProperties.material_mixture import parse_all_compositions_from_yaml
from starterDD.GeometryAnalysis.tdt_parser import read_material_mixture_indices_from_tdt_file
from starterDD.DDModel.DragonModel import CartesianAssemblyModel, FuelPinModel
from starterDD.DDModel.helpers import associate_material_to_rod_ID

# Goal : Create an assembly model and instantiate the Dragon Calculation Scheme builder
# Model instantiation steps :
flux_tracking_option = "TISO"  # Tracking type for the assembly model
flux_solution = "IC" 
# import macros : true
include_macros = True
path_to_yaml_compositions = "BWRProgressionProblems/GE14/inputs/material_compositions.yaml"
path_to_yaml_geometry = "BWRProgressionProblems/GE14/inputs/simplified_geometry.yaml"
path_to_tdt = "../../glow_data/tdt_data"
tdt_file_name = "GE14_simplified"

# Step 1 : Recover material compositions from the yaml file


compositions = parse_all_compositions_from_yaml(path_to_yaml_compositions)
# Step 2 : Recover material numbering from the tdt file generated by glow.

print([comp.material_name for comp in compositions])
material_mixtures_indices_dict = read_material_mixture_indices_from_tdt_file(path_to_tdt, 
                                                                    tdt_file_name=tdt_file_name, 
                                                                    tracking_option=flux_tracking_option, 
                                                                    include_macros=include_macros, 
                                                                    material_names=[comp.material_name for comp in compositions]
                                                                    )
print(material_mixtures_indices_dict)

# Step 3 : Create the assembly model with the given tdt file and lattice description.
# use CartesianAssemblyModel class method to create the zone_assignment properties.
ROD_to_material = associate_material_to_rod_ID(path_to_yaml_compositions,
                                               path_to_yaml_geometry)

GE14_simple_assembly = CartesianAssemblyModel(name="GE14_simple_assembly",
                                    tdt_file=path_to_tdt + "/" + tdt_file_name + ".tdt",
                                    geometry_description_yaml=path_to_yaml_geometry)
GE14_simple_assembly.set_rod_ID_to_material_mapping(ROD_to_material)
GE14_simple_assembly.set_uniform_temperatures(fuel_temperature=900.0, gap_temperature=600.0, coolant_temperature=600.0,moderator_temperature=600.0, structural_temperature=600.0, )
print(GE14_simple_assembly.rod_ID_to_material_dict)
print(GE14_simple_assembly.lattice_description)
GE14_simple_assembly.analyze_lattice_description(build_pins=True)
print(GE14_simple_assembly.lattice)

# set the material compositions in the assembly model
GE14_simple_assembly.set_material_compositions(compositions)

# Step 4 : Create material mixtures for the different materials in the assembly based on the selected property assignment strategy.
GE14_simple_assembly.number_fuel_material_mixtures(numbering_strategy="by_material")

print(GE14_simple_assembly.get_fuel_material_mixture_names())
print(GE14_simple_assembly.get_fuel_material_mixture_indices())
print(GE14_simple_assembly.get_fuel_material_mixtures())

# Step 5 : Instantiate the Dragon Calculation Scheme builder with the assembly model and build the calculation scheme.   


