# Functionnalities to parse tdt files generated by glow to extract relevant information.
# Decoupled from geometry builder to avoid requiring SALOME dependencies.



def read_material_mixture_indices_from_tdt_file(tdt_file_path, tdt_file_name, tracking_option, include_macros=False, material_names=None):
    """
    Read a TDT file and return the parsed data structure.
    Parameters:
    -----------
    tdt_file_path : str
        Path to the TDT file to be read
    Returns:
    --------
    dict
        Parsed TDT data structure
    """
    full_path = f"{tdt_file_path}/{tdt_file_name}_{tracking_option}"
    if include_macros:
        full_path += "_MACRO"
    full_path += ".dat"
    with open(full_path, 'r') as file:
        tdt_data = file.read()
    
    # parse lines that would correspond to material definitions in the TDT file and extract material indices
    # format is # <material_mixture_index>  - <material_name>
    extracted_material_mixture_indices = {}
    for line in tdt_data.splitlines():
        if material_names is not None:
            if any(mat_name in line for mat_name in material_names): # Need to be able to identify material composition for individual material mixtures.
                print(f"Line containing material name found: {line}")
                # recover material mixture index from line                
                parts = line.split()
                print(f"Parts: {parts}")
                mat_name = parts[-1]
                mat_index = parts[1]
                print(f"Material name: {mat_name}, Material mixture index: {mat_index}")
                extracted_material_mixture_indices[mat_name] = mat_index

        else:
            print(f"Line: {line}")
    return extracted_material_mixture_indices