# Functionnalities to parse tdt files generated by glow to extract relevant information.
# Decoupled from geometry builder to avoid requiring SALOME dependencies.

import re

def read_material_mixture_indices_from_tdt_file(tdt_file_path, tdt_file_name, tracking_option, include_macros=False, material_names=None):
    """
    Read a TDT .dat file and extract the material-mixture-name to integer-index mapping.

    The mapping is written by glow at the end of the .dat file as comment lines of the form::

        #  <index> - <unique_material_mixture_name>

    For example::

        #  1 - COOLANT
        #  5 - UOX16_zone_1

    Parameters
    ----------
    tdt_file_path : str
        Directory containing the .dat file.
    tdt_file_name : str
        Base name of the TDT file (without tracking/macro suffix or extension).
    tracking_option : str
        Tracking type appended to the file name (e.g. "TISO", "TSPC").
    include_macros : bool, optional
        If True, ``_MACRO`` is appended to the file name before the extension.
    material_names : list[str] or None, optional
        If provided, only entries whose unique name contains one of these base
        material names are returned (useful for filtering fuel-only entries).
        If None, *all* entries found in the file are returned.

    Returns
    -------
    dict[str, int]
        Mapping of ``unique_material_mixture_name`` → ``material_mixture_index``
        (index is an int, as used by DRAGON).
    """
    full_path = f"{tdt_file_path}/{tdt_file_name}_{tracking_option}"
    if include_macros:
        full_path += "_MACRO"
    full_path += ".dat"

    with open(full_path, 'r') as file:
        tdt_data = file.read()

    # Regex anchored to the exact comment format produced by glow:
    #   "#" then optional whitespace, then an integer, then " - ", then the name
    pattern = re.compile(r'^\s*#\s+(\d+)\s+-\s+(\S+)\s*$')

    extracted = {}
    for line in tdt_data.splitlines():
        m = pattern.match(line)
        if m:
            mix_index = int(m.group(1))
            mix_name = m.group(2)
            extracted[mix_name] = mix_index

    # Optional filtering by base material names
    if material_names is not None:
        filtered = {}
        for mix_name, mix_index in extracted.items():
            if any(base_name in mix_name for base_name in material_names):
                filtered[mix_name] = mix_index
        return filtered

    return extracted